language: python
python:
- 3.4
sudo: required
dist: trusty
before_install:
- sudo pip install ansible==2.1.3.0
install:
- env | sort
- ansible-playbook -vvv --extra-vars="brozzler_pip_name=file://$TRAVIS_BUILD_DIR#egg=brozzler user=travis" --inventory-file=ansible/hosts-localhost ansible/playbook.yml
- env | sort
- pip install $TRAVIS_BUILD_DIR pytest
- ls -l /opt /opt/*/bin /opt/*/lib/python3.4/site-packages
script:
- py.test -v -s tests
after_failure:
- ls -l /opt
- sudo cat /var/log/upstart/warcprox.log
- sudo cat /var/log/upstart/brozzler-worker.log
- sudo cat /var/log/upstart/pywb.log

