---
- name: ensure rethinkdb apt public key is trusted
  apt_key: url=http://download.rethinkdb.com/apt/pubkey.gpg
  become: true
- name: ensure rethinkdb repo is in apt sources.list
  apt_repository: repo='deb http://download.rethinkdb.com/apt trusty main'
                  state=present
  become: true
- name: ensure rethinkdb package is installed
  apt: name=rethinkdb state=present
  become: true
  notify:
  - restart rethinkdb
# XXX rethinkdb fails to start in spite of this, I think because /vagrant
# gets mounted too late, and it tries to log there
- name: ensure rethinkdb starts on reboot
  service: name=rethinkdb enabled=yes
- name: ensure rethinkdb instance config file is installed
  template: src=templates/rethinkdb-brozzler-vagrant-1.conf.j2
            dest=/etc/rethinkdb/instances.d/rethinkdb-brozzler-vagrant-1.conf
  become: true
  notify:
  - restart rethinkdb
