---
- name: ensure required packages are installed
  become: true
  apt: name={{item}} state=present
  with_items:
    - gcc
    - python-virtualenv
    - python3.4
    - libpython3.4-dev
    - libffi-dev
    - libssl-dev
    - tor
    - git
- name: install warcprox in virtualenv
  pip: name=git+https://github.com/internetarchive/warcprox.git@2.x#egg=warcprox
       virtualenv=/home/vagrant/warcprox-ve34
       virtualenv_python=python3.4
       extra_args='--no-input --upgrade --pre'
  notify:
    - restart warcprox
- name: install upstart config /etc/init/warcprox.conf
  become: true
  template: src=templates/warcprox.conf.j2 dest=/etc/init/warcprox.conf
  notify:
    - restart warcprox
