---
- name: install pywb in virtualenv
  pip: name=pywb
       virtualenv=/home/vagrant/pywb-ve34
       virtualenv_python=python3.4
       extra_args='--no-input --upgrade --pre'
  notify:
  - restart pywb
- name: install brozzler in pywb virtualenv
  pip: name='-e /brozzler'
       virtualenv=/home/vagrant/pywb-ve34
       virtualenv_python=python3.4
       extra_args='--no-input --upgrade --pre'
  notify:
  - restart pywb
- name: pywb config file /etc/pywb.yml
  template: src=templates/pywb.yml.j2
            dest=/etc/pywb.yml
  become: true
  notify:
  - restart pywb
- name: upstart config file /etc/init/pywb.conf
  template: src=templates/pywb.conf.j2
            dest=/etc/init/pywb.conf
  become: true
  notify:
  - restart pywb
