---
- name: install brozzler[webconsole] in virtualenv
  become: true
  pip: name='-e /brozzler[webconsole]'
       virtualenv=/home/vagrant/brozzler-webconsole-ve34
       virtualenv_python=python3.4
       extra_args='--no-input --upgrade --pre'
  notify:
  - restart brozzler-webconsole
- name: install upstart config /etc/init/brozzler-webconsole.conf
  become: true
  template: src=templates/brozzler-webconsole.conf.j2
            dest=/etc/init/brozzler-webconsole.conf
  notify:
  - restart brozzler-webconsole